apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: argocd
  namespace: openshift-gitops
spec:
  description: Core Argocd
  sourceRepos:
  - '*'
  destinations:
  - namespace: openshift-gitops
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: false